name: Docker python app push

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read



jobs:
  build:
    runs-on: ubuntu-latest
      d

      steps:
        d
        - uses: actions/checkout@v2
        name: Check out code

        - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          d
          image: nitch425/test_repo_piplines
        tags: v1.2
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
