name: Python testing application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setting up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Testing python3
      run: |
        echo "hello from runners!!"
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: nitch425/test_repo_piplines
        tags: v2.0
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
